### ISSUE TITLE
npm run ngc error

### ISSUE THREAD

**Issue by qk44077907** [Quramy/ng2-lazy-load-demo#1]
Error: Error at C:/AmateurProject/ng2-lazy-load-demo-master/src/index-aot.ts:7:3
    at check (C:\AmateurProject\ng2-lazy-load-demo-master\node_modules\@angular\
    at Tsc.typeCheck (C:\AmateurProject\ng2-lazy-load-demo-master\node_modules\@
    at C:\AmateurProject\ng2-lazy-load-demo-master\node_modules\@angular\tsc-wra
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:445:3
Compilation failed

**Comment by Quramy** [comment]
I've added `index-aot.ts` to exclude list of `tsconfig.json at 9bb6afe57be2e70d4a3be58bb949182df347ebc9 . It'll suppress your compilation error.

**Comment by qk44077907** [comment]
@Quramy sorry,anthor error when excuting ngc:
metadata emit requires the sourceFiles are passed to WriteFileCallback. Update to TypeScript ^1.9.0-dev

so i tried to change the typescript version to  "^1.9.0-dev" in package.json ,it works now.but i dont know why in details

**Comment by Quramy** [comment]
The compiler CLI uses some typescript APIs. But in the latest version of typescript(this repo had used), perhaps these APIs were removed.

Yesterday I've fixed package.json to use the correct version(2.0.2).
